Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,12 +41,17 @@ jobs:
       - name: Deploy to Vercel
         env:
           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
-        run: npx vercel deploy VTI-frontend/ --prod --yes --token=$VERCEL_TOKEN 
-        
-      - name: Assign Alias
-        env:
-          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
-        run: npx vercel alias vti-frontend.vercel.app --token=$VERCEL_TOKEN
+        run: |
+          DEPLOYMENT_URL=$(npx vercel --prod --token=$VERCEL_TOKEN --output=json | jq -r '.url')
+          
+          if [ -n "$DEPLOYMENT_URL" ]; then
+            echo "Deployment URL: $DEPLOYMENT_URL"
+            npx vercel alias $DEPLOYMENT_URL vti-frontend.vercel.app --token=$VERCEL_TOKEN
+          else
+            echo "Deployment failed or no URL returned."
+            exit 1
+          fi
+
 
 
       - name: Run Cypress tests
